version: "3.7"

services:
    mempool_api:
        image: "samouraiwallet/dojo-mempool_api:${DOJO_MEMPOOL_API_VERSION_TAG}"
container_name: "mempool_api"
        args:
            MEMPOOL_API_LINUX_UID: ${MEMPOOL_API_LINUX_UID}
            MEMPOOL_API_LINUX_GID: ${MEMPOOL_API_LINUX_GID}
        restart: on-failure
        stop_grace_period: 1m
        command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
        volumes:
            - data-mempool-api:/backend/cache
        env_file:
            - ./.env
            - ./conf/docker-mysql.conf
            - ./conf/docker-bitcoind.conf
            - ./conf/docker-indexer.conf
            - ./conf/docker-mempool.conf
        depends-on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "10"
        networks:
            dojonet:
                ipv4_address: ${NET_DOJO_MEMPOOL_API_IPV4}

    mempool_web:
       image: "samouraiwallet/dojo-mempool_web:${DOJO_MEMPOOL_WEB_VERSION_TAG}"
container_name: "mempool_web"
        args:
            MEMPOOL_WEB_LINUX_UID: ${MEMPOOL_WEB_LINUX_UID}
            MEMPOOL_WEB_LINUX_GID: ${MEMPOOL_WEB_LINUX_GID}
        restart: on-failure
        stop_grace_period: 1m
        command: "./wait-for db:3306 --timeout=720 -- strict --- ./start.sh"
        ports:
            - 8051:8080
        env_file:
            - ./.env
            - ./conf/docker-mysql.conf
            - ./conf/docker-bitcoind.conf
            - ./conf/docker-nginx.conf
            - ./conf/docker-indexer.conf
        FRONTEND_HTTP_PORT: "8080"
        BACKEND_MAINNET_HTTP_HOST: "mempool_api"
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "10"
        depends_on:
            - tor
            - nginx
            - mempool_api
            - db
        volumes:
            - data-mempool-web:/mempool/data
        networks:
            dojonet:
                ipv4_address: ${NET_DOJO_MEMPOOL_WEB_IPV4}