services:
  soroban:
    image: "samouraiwallet/dojo-soroban:${DOJO_SOROBAN_VERSION_TAG}"
    container_name: soroban
    build:
      context: ./soroban
      args:
        SOROBAN_LINUX_UID: ${SOROBAN_LINUX_UID}
        SOROBAN_LINUX_GID: ${SOROBAN_LINUX_GID}
        SOROBAN_TOR_LINUX_UID: ${SOROBAN_TOR_LINUX_UID}
        SOROBAN_TOR_LINUX_GID: ${SOROBAN_TOR_LINUX_GID}
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-soroban.conf
    restart: always
    expose:
      - "${SOROBAN_PORT}"
    volumes:
      - data-soroban:/home/soroban/data
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      dmznet:
        ipv4_address: ${NET_DMZ_SOROBAN_IPV4}
      dojonet:
        ipv4_address: ${NET_DOJO_SOROBAN_IPV4}

volumes:
  data-soroban:
